// create a array of data:

// importing Mobile and MobileDescModel:
const MobileModel = require("../models/mobile-model");
// const MobileDescModel = require("../models/mobile-desc-model");

// TODO: This has to come from a DB:
module.exports = [
  new MobileModel(
    1,
    "Apple iPhone 11",
    "Apple iPhone 11 IOS Smartphone",
    "https://rukminim1.flixcart.com/image/416/416/k2jbyq80pkrrdj/mobile-refurbished/x/j/s/iphone-11-128-d-mwm02hn-a-apple-0-original-imafkg242ugz8hwc.jpeg?q=70", // mobile-image
    "[good ,awesome, okok]",
    "3",
    "71600",
    "3",
    "[3,5,3]",
    "3.3",
    "",

    "https://rukminim1.flixcart.com/image/200/200/cms-rpd-images/05f1a201c8774bc7b1604acc20de1fd4_16d485a3e52_image.jpeg?q=90",
    "https://rukminim1.flixcart.com/image/200/200/cms-rpd-images/c1e168ff0ba0498d875fc8723c95f093_16d48598a68_image.jpeg?q=90",
    "https://rukminim1.flixcart.com/image/200/200/cms-rpd-images/93677ca4717f44f496bfbb1f228c2d61_16d485af9df_image.jpeg?q=90",
    "https://rukminim1.flixcart.com/image/200/200/cms-rpd-images/aed67c00e85f4c0f950f6d2ca91639df_16d4859f4de_image.jpeg?q=90",
    "https://rukminim1.flixcart.com/image/200/200/cms-rpd-images/0c6e413421744c52b04336b59ecbe9d5_16d485a18c8_image.jpeg?q=90",
    "https://rukminim1.flixcart.com/image/200/200/cms-rpd-images/9490ec20393b496fa9f270d715bba3f9_16d4859a41c_image.jpeg?q=90",
    "",
    "",
    "Privacy is Built-in",
    "Face ID is one of the most secure facial authentication methods in a smartphone. It doesn’t store or share your photo. And, it’s more secure than Touch ID.",
    "Battery + Performance: Power Through Your Day",
    "All-day battery life. A13 Bionic chip is the fastest chip in a smartphone. Fast-charge capable with an 18 W adapter (sold separately).",
    "Take Your Photos Further. And Wider.",
    "The iPhone 11 features dual 12 MP Ultra Wide (13mm) and Wide (26mm) cameras with 4K video recording up to 60 fps. The Ultra Wide camera provides 120° field of view, letting you capture four times more scene, and the Wide camera provides 100% Focus Pixels for up to three times faster autofocus in low light.",
    "Night Mode - Night, in a New Light.",
    "Whether it’s candle-lit birthdays or campfires on the beach, the new Night mode delivers natural low-light shots - automatically.",
    "Take Your Video Up a Notch",
    "Get ready to enjoy 4K video at 60 fps on every camera. Ultra Wide camera for four times more scene. Rotate, crop and add filters as easily as you do with photos.",
    "Beautiful Design",
    "Featuring a 15.49-cm (6.1) all-screen Liquid Retina LCD and a glass and aluminum design, the iPhone 11 is as beautiful as it gets. Also, the IP68 rating ensures that is water-resistant up to 2 meters for 30 minutes.",
    "",
    "",
    "",
    "",
    "Handset, EarPods with Lightning Connector, Lightning to USB Cable, USB Power Adapter, Documentation",
    "MWM02HN/A",
    "iPhone 11",
    "White",
    "Smartphones",
    "Dual Sim",
    "No",
    "Yes",
    "No",
    "",
    "15.49 cm (6.1 inch)",
    "1792 x 828 Pixels",
    "Liquid Retina HD Display",
    "326 PPI",
    "",
    "1400:1 Contrast Ratio (Typical), True Tone Display, Wide Colour Display (P3), Haptic Touch, 625 nits Max Brightness (Typical), Fingerprint Resistant Oleophobic Coating, Support for Display of Multiple Languages and Characters Simultaneously",
    "iOS 13",
    "A13 Bionic Chip",
    "",
    "",
    "",
    "128 GB",
    "",
    "",
    "Yes",
    "12MP + 12MP",
    "Yes",
    "12MP Front Camera",
    true,
    "2020-09-08"
  ),
];
